version: '3.5'
services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    image: nginx
    container_name: p20-nginx
    ports:
      - 80:80
    depends_on:
      - api
      - web
  api:
    build:
      context: .
      dockerfile: strapi.Dockerfile
    image: p20-backend
    container_name: p20-backend
    command: sh -c "yarn start"
    depends_on:
      - db
  db:
    image: mongo
    container_name: p20-db
    volumes:
      - data:/data/db
volumes:
  data:
    external:
      name: p20-website_data
