version: '3.5'
services:
  nginx:
    build:
      context: ../p20-backend
      dockerfile: nginx.Dockerfile
    image: nginx
    container_name: p20-nginx
    ports:
      - 80:80
    depends_on:
      - api
      - web
  api:
    build:
      context: ../p20-backend
      dockerfile: strapi.Dockerfile
    container_name: p20-backend
    command: sh -c "yarn start"
    depends_on:
      - db
  api-dev:
    build:
      context: ../p20-backend
      dockerfile: strapi.Dockerfile
      args:
        - NODE_ENV=staging
    environment:
      - NODE_ENV=staging
    container_name: p20-backend-dev
    command: sh -c "DB_NAME=p20-backend-dev yarn start"
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: mongo
    container_name: p20-db
    volumes:
      - data:/data/db
volumes:
  data:
    external:
      name: p20-website_data
