version: '3.5'
services:
  db:
    image: mongo
    container_name: p20-db-dev
    command: "--smallfiles --logpath=/dev/null"
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
volumes:
  data:
    external:
      name: p20-website_data